<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./MyStyle.css">
    <title>Home</title>
</head>

<body>

    <?php include 'Header.PHP';?>

    <a href="./2.Roadmap.PHP"><img width="100%" src="./img/indexPage.jpg" alt="ITI Alexandria CMS Track Roadmap"></a>

    <?php include 'Footer.PHP';?>
</body>

</html>