<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./MyStyle.css">
    <title>Roadmap</title>
    <!-- <style>
        .flex-container {
            display: flex;
            background-color: DodgerBlue;
        }
        .flex-container > div {
            background-color: #f1f1f1;
            margin: 10px;
            padding: 20px;
            font-size: 30px;
            flex: 50%;
        }
        .flex-container {
        display: flex;
        flex-wrap: wrap;
        }

        .flex-item-left {
        flex: 50%;
        }

        .flex-item-right {
        flex: 50%;
        }
        .footer{
            color:blue
        }
    </style> -->
</head>

<body>

    <!-- <header>
        <div class="main">
            <nav>
                <ul>
                    <li><a href="./1.Index_Home.html" title="ITI Landing Home Page">Home</a></li>
                    <li><a href="./2.Roadmap.html" title="ITI Alexandria CMS Track Roadmap">Roadmap</a></li>
                    <li><a href="./3.Registration Form.html"
                            title="ITI Alexandria CMS Track Registration Form">Registration Form</a></li>
                    <li><a href="https://www.iti.gov.eg" title="ITI Site" target="_blank">Contact</a></li>
                </ul>
            </nav>
            <img src="./img/ITI_logo.png" alt="ITI Logo" width="200">
        </div>
    </header> -->
    <?php include 'Header.PHP';?>

    <h1 style="color:red; text-align: center; font-size:30px;">Technical Road-Map Syllabus</h1>
    <p>Product oriented approach that gives you the skills to build a
        <span style="color:red; text-align: center;"><b><i><u>Website for Business Company</u></i> .</b></span>
    </p>
    <h3>CMS track categories:</h3>
    <ol>
        <li>Web fundamentals.</li>
        <li>Database.</li>
        <li>Administration.</li>
        <li>Software development using PHP.</li>
        <li>Content management systems.</li>
        <li>Employability skills.</li>
    </ol>

    <div class="flex-container">
        <div class="flex-item-left">
            <h3>Web fundamentals.</h3>
            <ul>
                <li>HTML/CSC</li>
                <li>Java Script</li>
            </ul>
            <h3>Database.</h3>
            <ul>
                <li>MySQL Database</li>
            </ul>
            <h3>Administration.</h3>
            <ul>
                <li>Introduction to Apache Web server.</li>
            </ul>
        </div>

        <div class="flex-item-right">
            <h3>Software development using PHP.</h3>
            <ul>
                <li>PHP programming language.</li>
            </ul>
            <h3>Content management systems.</h3>
            <ul>
                <li>WordPress.</li>
                <li>Joomla.</li>
            </ul>
            <h3>Employability skills.</h3>
            <ul>
                <li>Effective communication skills.</li>
                <li>Effective presentation skills.</li>
                <li>Interviewing skills.</li>
                <li>Freelancing skills.</li>
            </ul>
        </div>
    </div>
    <p>For more details visit our <a href="https://www.iti.gov.eg/">ITI</a> web site.</p>
    <!-- <h2 style="text-align: center;"> <a href="#"> Top </a> </h2> -->
    <h2>
        <Center><a href="#"> Top </a></Center>
    </h2>
    <hr>
    <!-- <footer class="footer" style="color: blue; text-align: center;"> Copyright 2023 by Ahmed Saber &#174;. All Rights Reserved </footer>         -->
    <!-- <footer class="footer">
        <center>Copyright 2023 by Ahmed Saber &#174;. All Rights Reserved</center>
    </footer> -->
<?php include 'Footer.PHP';?>
</body>
</html>
