<!-- Header -->

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./MyStyle.css">
    <title>Home</title>
</head>
<body> -->

<header>
    <div class="main">
        <nav>
            <ul class="list-inline">
                <li class="list-inline-item" /*id="active"*/><a href="./1.Home.PHP" title="ITI Landing Home Page">Home</a></li>
                <li class="list-inline-item" /*id="active"*/><a href="./2.Roadmap.PHP" title="ITI Alexandria CMS Track Roadmap Page">Roadmap</a></li>
                <li class="list-inline-item" /*id="active"*/><a href="./3.Registration Form.PHP"
                        title="ITI Alexandria CMS Track Student Registration Form Page">Registration Form</a></li>
                <li class="list-inline-item" /*id="active"*/><a href="https://www.iti.gov.eg" title="ITI Site" target="_blank">Contact</a></li>

                <!-- SCRUD Application -->
                <li class="list-inline-item" /*id="active"*/><a href="./Employees Details CRUD List.php"
                        title="ITI Employees Details CRUD List Page">Employees Details CRUD List</a></li>

                <!-- Ajax Live Search -->

                <!-- Login System -->
                <li class="list-inline-item" /*id="active"*/><a href="./register.php" title="ITI User Register Page">Register</a>
                </li>
                <li class="list-inline-item" /*id="active"*/><a href="./login.php" title="ITI User Login Home Page">Login</a></li>
            </ul>
        </nav>
        <img class="logo" src="./img/ITI_logo.png" alt="ITI Logo" width="200">
    </div>
</header>